apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-app
  labels:
    app: restaurant-app  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-app
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
      - name: restaurant-app
        image: runtesting/restaurant-app:latest
        ports:
        - containerPort: 80