apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  labels:
    app: restaurant-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: restaurant-app
